name: Check Pull Request

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: "3.x"
      - uses: actions/cache@v1
        with: # Later, make this an anchor
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('setup.py') }}
          restore-keys: |
            pip-${{ runner.os }}-
            pip-
      - name: Run lint
        run: |
          python -m pip install -U tox
          tox -e lint
  test:
    needs: lint
    strategy:
      matrix:
        python: ["2.7", "3.5", "3.6", "3.7", "3.8"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}
      - uses: actions/cache@v1
        with: # Make anchor reference
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('setup.py') }}
          restore-keys: |
            pip-${{ runner.os }}-
            pip-
      - name: Run test
        run: |
          python -m pip install tox
          tox -e py
        env:
          COVERAGE_FILE: .coverage.${{ matrix.python }}.${{ runner.os }}
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: coverage-results
          path: .coverage.${{ matrix.python }}.${{ runner.os }}
        if: matrix.python != '3.4'  # 3.4 doesn't support newer coverage
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: "3.x"
      - uses: actions/cache@v1
        with: # Make anchor reference
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('setup.py') }}
          restore-keys: |
            pip-${{ runner.os }}-
            pip-
      - uses: actions/download-artifact@master
        with:
          name: coverage-results
      - name: Run coverage
        run: |
          python -m pip install tox
          mv coverage-results/.coverage.* .
          tox -e coverage
