name: Release Time!

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@master
        with:
          python-version: "3.x"
      - name: Build
        run: |
          python -m pip install -U pip setuptools
          pip install -U wheel
          python setup.py build sdist bdist_wheel
      - name: Get tag name
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - name: GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.get_tag.outputs.TAG }}
          draft: false
          prerelease: false
      - name: Upload wheel to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/stream_redirect-${{ steps.get_tag.outputs.TAG }}-py3-none-any.whl
          asset_name: stream_redirect-${{ steps.get_tag.outputs.TAG }}-py3-none-any.whl
          asset_content_type: application/zip
      - name: Upload tarball to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/stream-redirect-${{ steps.get_tag.outputs.TAG }}.tar.gz
          asset_name: stream-redirect-${{ steps.get_tag.outputs.TAG }}.tar.gz
          asset_content_type: application/x-compressed-tar
      - name: PyPI release
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
